K-asa/urls.py
from django.urls import path

app_name = "K-asa"

urlpatterns = [

]

Kasa/urls.py
from django.urls import path
from Kasa import views

app_name = 'Kasa'

urlpatterns = [
    path('', views.main, name='main'),
    path('search/', views.search, name='search'),
    path('song/<int:song_pk>/', views.song_detail, name='song_detail'),
    path('singer/<int:singer_pk>', views.singer_detail, name='singer_detail'),
    path('group/<int:group_pk>', views.group_detail, name='group_detail'),
    path('album/<int:album_pk>', views.album_detail, name='album_detail'),
    path('comment/new/', views.write_new_comment, name='write_new_comment'),
    path('edit/<int:song_id>/stage1/', views.enter_all_lyrics, name='enter_all_lyrics'),
    path('edit/<int:song_id>/stage2/', views.modify_and_create_each_lyrics, name='modify_and_create_each_lyrics'),
]

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('reset_pw/', views.reset_pw.as_view(), name='reset_pw'),
    path('reset_pw/done/', views.reset_pw_done.as_view(), name='reset_pw_done'),
    path('reset/<uidb64>/<token>/', views.reset_pw_confirm.as_view(), name='reset_pw_confirm'),
    path('reset_pw/complete/', views.reset_pw_complete.as_view(), name='reset_pw_complete'),
    path('change_info/', views.change_info, name='change_info'),
    path('check_comment/', views.check_comment, name='check_comment'),
    path('check_comment/del/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
]

Kasa/models.py
from django.db import models
from accounts.models import User


class Groups(models.Model):
    gname = models.CharField(max_length=255, verbose_name='그룹이름')
    agency = models.CharField(max_length=255, blank=True, verbose_name='소속사')
    sns_url = models.URLField(verbose_name='SNS', blank=True)
    group_image = models.ImageField(upload_to='group_image', blank=True, verbose_name='그룹사진')
    debut = models.DateField(verbose_name='데뷔일')

    def __str__(self):
        return self.gname


class Albums(models.Model):
    aname = models.CharField(max_length=255, verbose_name='앨범이름')
    release_date = models.DateField(verbose_name='발매일')
    album_art = models.ImageField(upload_to="album_art", verbose_name='자켓사진')
    content = models.TextField(blank=True, verbose_name='앨범소개')
    group = models.ForeignKey(Groups, on_delete=models.CASCADE, verbose_name='그룹이름', related_name='group_album')

    def __str__(self):
        return self.aname


class Singers(models.Model):
    sname = models.CharField(max_length=255, verbose_name='가수이름')
    birth = models.DateField(blank=True, verbose_name='생일')
    image = models.ImageField(upload_to='singer_image', blank=True, verbose_name='가수사진')
    wiki_url = models.URLField(blank=True, verbose_name='가수정보')
    group = models.ManyToManyField(Groups, verbose_name='소속그룹', related_name='group_singer')
    active_date = models.DateField(blank=True, null=True, verbose_name='활동년대')
    nationality = models.CharField(max_length=255, blank=True, verbose_name='국적')
    constellation = models.CharField(max_length=255, blank=True, verbose_name='별자리')
    content = models.TextField(blank=True, verbose_name='가수소개')


    def __str__(self):
        return self.sname


class Songs(models.Model):
    sname = models.CharField(max_length=255, verbose_name='노래제목')
    youtube_url = models.URLField(blank=True, verbose_name='뮤직비디오')
    soundcloud_url = models.URLField(blank=True, verbose_name='오디오')
    dance_url = models.URLField(blank=True, verbose_name='무대영상')
    album = models.ForeignKey(Albums, on_delete=models.CASCADE, verbose_name='앨범', related_name='album_song')
    singer = models.ManyToManyField(Singers, verbose_name='가수', related_name='singer_song')
    view_count = models.IntegerField(default=0, verbose_name='조회수')

    def __str__(self):
        return self.sname


class Comments(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자', related_name='user_comment')
    song = models.ForeignKey(Songs, on_delete=models.CASCADE, verbose_name='노래', related_name='song_comment')

    def __str__(self):
        return self.content

class Lyrics(models.Model):
    kor = models.TextField(verbose_name='한국어')
    eng = models.TextField(blank=True, verbose_name='영어')
    rom = models.TextField(blank=True, verbose_name='로마자')
    fanchant = models.TextField(blank=True, verbose_name='응원법')
    order = models.IntegerField(verbose_name='순서')
    song = models.ForeignKey(Songs, on_delete=models.CASCADE, verbose_name='노래', related_name='song_lyrics')
    singer = models.ManyToManyField(Singers, blank=True, verbose_name='파트', related_name='singer_lyrics')

    def __str__(self):
        return self.song.sname + str(self.order)


class Explanations(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정일')
    content = models.TextField(verbose_name='내용')
    image = models.ImageField(upload_to='explanation_image', blank=True, verbose_name='사진')
    likes = models.IntegerField(default=0, editable=False, verbose_name='좋아요')
    lyrics = models.OneToOneField(Lyrics, on_delete=models.CASCADE, verbose_name='가사', related_name='lyrics_explanation')

    def __str__(self):
        return self.content

Kasa/forms.py
from accounts import forms

Kasa/views.py
import json
import random
import requests
from bs4 import BeautifulSoup
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from Kasa.convert_url import convert_youtube
from Kasa.models import *
from django.db.models import Q
from django.core.paginator import Paginator


def song_detail(request, song_pk):
    song = get_object_or_404(Songs, pk=song_pk)
    song.view_count += 1
    song.save()

    album = song.album
    sns = song.album.group.sns_url
    youtube_url = convert_youtube(song.youtube_url)
    soundcloud_url = convert_youtube(song.soundcloud_url)
    dance_url = convert_youtube(song.dance_url)
    all_lyrics = song.song_lyrics.all()
    comments = song.song_comment.all().order_by('-created_at')
    members = song.album.group.group_singer.all()

    context = {
        'song': song,
        'album': album,
        'comments': comments,
        'youtube_url': youtube_url,
        'dance_url': dance_url,
        'soundcloud_url': soundcloud_url,
        'sns': sns,
        'all_lyrics': all_lyrics,
        'members': members,
    }
    return render(request, 'Kasa/song_detail.html', context)


def write_new_comment(request):
    if request.method == "POST":
        song = get_object_or_404(Songs, pk=request.POST.get('song_id', None))
        Comments.objects.create(content=request.POST.get('comment_content', ''), user=request.user, song=song)
        return redirect('Kasa:song_detail', song.pk)


def enter_all_lyrics(request, song_id):
    if request.method == "POST":
        song = Songs.objects.get(pk=song_id)
        singers = Singers.objects.filter(singer_song=song_id)
        all_kor = request.POST.get('all_kor', None).split('\r\n')
        all_lang_dict = {}
        length = len(all_kor)

        for index, lyrics in enumerate(all_kor):
            all_lang_dict[str(index + 1)] = {'kor': lyrics}

        eng_request = request.POST.get('all_eng', None)
        if eng_request:
            all_eng = eng_request.split('\r\n')
            if len(all_eng) > length:
                context = {
                    'error': 'English lyrics too Long!',
                    'all_kor': request.POST['all_kor'],
                    'all_eng': request.POST['all_eng'],
                    'all_rom': request.POST['all_rom'],
                }
                return render(request, 'Kasa/enter_all_lyrics.html', context)

            for index, lyrics in enumerate(all_eng):
                location = all_lang_dict.get(str(index + 1), None)
                location['eng'] = lyrics

        rom_request = request.POST.get('all_rom', None)
        if rom_request:
            all_rom = rom_request.split('\r\n')
            if len(all_rom) > length:
                context = {
                    'error': 'Romanized lyrics too Long!',
                    'all_kor': request.POST['all_kor'],
                    'all_eng': request.POST['all_eng'],
                    'all_rom': request.POST['all_rom'],
                }
                return render(request, 'Kasa/enter_all_lyrics.html', context)
            for index, lyrics in enumerate(all_rom):
                location = all_lang_dict.get(str(index + 1), None)
                location['rom'] = lyrics

        context = {
            'song': song,
            'singers': singers,
            'all_lang_dict': all_lang_dict,
            'length': length,
        }
        return render(request, 'Kasa/modify_and_create_each_lyrics.html', context)
    else:
        song = Songs.objects.get(id=song_id)
        all_lyrics = song.song_lyrics.all()
        all_kor = ''
        all_eng = ''
        all_rom = ''
        if len(all_lyrics):
            for lyrics in all_lyrics:
                all_kor += lyrics.kor + '\n'
                all_eng += lyrics.eng + '\n'
                all_rom += lyrics.rom + '\n'

        context = {
            'all_kor': all_kor,
            'all_eng': all_eng,
            'all_rom': all_rom,
        }
        return render(request, 'Kasa/enter_all_lyrics.html', context)


def modify_and_create_each_lyrics(request, song_id):
    if request.method == "POST":
        request_dict = request.POST
        song = Songs.objects.get(pk=song_id)
        singers = song.singer.all()
        all_lyrics = song.song_lyrics.all().order_by('order')
        length = int(request.POST['length'])
        if all_lyrics:
            # DB에 저장된 노래가사들이 있을 경우
            existing_lyrics_length = len(all_lyrics)
            if existing_lyrics_length > length:
                # 새로 들어온 가사가 기존의 가사의 길이보다 작을 경우 삭제
                start = length
                end = existing_lyrics_length
                for over in range(start, end):
                    all_lyrics[over].delete()
            for input_order in range(0, length):
                str_input_order = str(input_order + 1)
                if input_order < existing_lyrics_length:
                    # 기존 순서의 가사가 있을 경우 변경
                    all_lyrics[input_order].kor = request_dict['kor' + str_input_order]
                    all_lyrics[input_order].order = input_order + 1
                    if request_dict['eng' + str_input_order]:
                        all_lyrics[input_order].eng = request_dict['eng' + str_input_order]
                    if request_dict['rom' + str_input_order]:
                        all_lyrics[input_order].rom = request_dict['rom' + str_input_order]
                    if request_dict.get('part' + str_input_order + '[]', False):
                        partList = request_dict.getlist('part' + str_input_order + '[]')
                        all_lyrics[input_order].singer.clear()
                        for member in singers:
                            if member.sname in partList:
                                all_lyrics[input_order].singer.add(member)
                    all_lyrics[input_order].save()
                else:
                    # 기존 순서에 없는 가사가 있을 경우 추가
                    new_lyrics = Lyrics.objects.create(kor=request_dict['kor' + str_input_order],
                                                       order=input_order + 1, song=song)
                    if request_dict['eng' + str_input_order]:
                        new_lyrics.eng = request_dict['eng' + str_input_order]
                    if request_dict['rom' + str_input_order]:
                        new_lyrics.rom = request_dict['rom' + str_input_order]
                    if request_dict.get('part' + str_input_order + '[]', False):
                        partList = request_dict.getlist('part' + str_input_order + '[]')
                        # all_lyrics[input_order].singer.clear()
                        for member in singers:
                            if member.sname in partList:
                                new_lyrics.singer.add(member)
                    new_lyrics.save()

        else:
            # 노래의 가사가 처음 등록되는 경우
            for input_order in range(0, length):
                str_input_order = str(input_order + 1)
                new_lyrics = Lyrics.objects.create(kor=request_dict['kor' + str_input_order],
                                                   order=input_order + 1, song=song)
                if request_dict['eng' + str_input_order]:
                    new_lyrics.eng = request_dict['eng' + str_input_order]
                if request_dict['rom' + str_input_order]:
                    new_lyrics.rom = request_dict['rom' + str_input_order]
                if request_dict.get('part' + str_input_order + '[]', False):
                    partList = request_dict.getlist('part' + str_input_order + '[]')
                    # all_lyrics[input_order].singer.clear()
                    for member in singers:
                        if member.sname in partList:
                            new_lyrics.singer.add(member)
                new_lyrics.save()

    return redirect('Kasa:song_detail', song.pk)


def search(request):
    kwd = request.GET.get('kwd', None)

    if not kwd:
        noresult = True

        context = {
            'kwd': kwd,
            'noresult': noresult,
        }
        return render(request, 'Kasa/search_detail.html', context)

    target = request.GET.get('target', '')

    singers_list = []
    songs_list = []
    lyrics_list = []
    albums_list = []
    groups_list = []

    singers = Singers.objects.filter(sname__icontains=kwd)
    songs = Songs.objects.filter(sname__icontains=kwd)
    lyrics = Lyrics.objects.filter(Q(kor__icontains=kwd) | Q(rom__icontains=kwd) | Q(eng__icontains=kwd))
    albums = Albums.objects.filter(aname__icontains=kwd)
    groups = Groups.objects.filter(Q(gname__icontains=kwd) | Q(agency__icontains=kwd))

    if singers:
        for singer in singers:
            singers_list.append(singer)
    if songs:
        for song in songs:
            songs_list.append(song)
    if albums:
        for album in albums:
            albums_list.append(album)
    if groups:
        for group in groups:
            groups_list.append(group)
    if lyrics:
        for overlap_check in lyrics:
            if overlap_check in lyrics_list:
                continue
            lyrics_list.append(overlap_check)

    # 그룹을 검색했을 때 해당 그룹의 앨범,노래,가수
    if groups:
        for group in groups:
            for group_singer in group.group_singer.all():
                singers_list.append(group_singer)
            for group_album in group.group_album.all():
                albums_list.append(group_album)
                for group_song in group_album.album_song.all():
                    songs_list.append(group_song)

    # 가수를 검색했을 때 해당 가수의 그룹,앨범
    if singers:
        for singer in singers:
            for singer_group in singer.group.all():
                groups_list.append(singer_group)
                for singer_album in singer_group.group_album.all():
                    albums_list.append(singer_album)

    # 앨범을 검색했을 때 해당 앨범의 그룹,노래
    if albums:
        for album in albums:

Kasa/templates/Kasa/detail_song.html
{{ album.aname }}
{{ album.release_date }}
{{ album.album_art }}


<div class="lyrics">
    {% for lyrics in all_lyrics %}
        <div>
            {{ lyrics.kor }}
        </div>
    {% endfor %}
</div>

<div class="twitter_url" style="height:500px; width: 300px; overflow-y: scroll; border: 1px solid black" ;>
    <a class="twitter-timeline" href="{{ sns }}">Tweets by BTS_twt</a>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

<iframe width="500" height="250" src="{{ youtube_url }}" frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


{% for comment in comments %}
    <div>{{ comment.content }}</div>
    <div>{{ comment.user.username }}</div>
    <div>{{ comment.created_at }}</div>
    <br/>
{% endfor %}


{% if user.is_authenticated %}
    <form action="{% url "Kasa:write_new_comment" %}" method="POST">
        {% csrf_token %}
        <input type="text" class="comment_content" name="comment_content" placeholder="댓글 작성" autocomplete="off">
        <input type="submit" class="submit" value="작성">
        <input type="hidden" class="song_id" name="song_id" value="{{ song.id }}">
    </form>
{% else %}
    <a href="{% url "accounts:login" %}">로그인</a>
{% endif %}

Kasa/templates/Kasa/enter_all_lyrics.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/enter_all_lyrics.css" %}"/>
{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="error">{{ error }}</div>

        <div class="inputlyricswrap">
            <div id="all_kor">
                <h2>Korean lyrics</h2>
                <textarea name="all_kor" class="all_kor">{{ all_kor }}</textarea>
            </div>
            <div id="all_eng" style="display:none;">
                <h2>English lyrics</h2>
                <textarea name="all_eng" class="all_eng" cols="40" rows="30">{{ all_eng }}</textarea>
            </div>
            <div id="all_rom" style="display:none;">
                <h2>Romanized lyrics</h2>
                <textarea name="all_rom" class="all_rom" cols="40" rows="30">{{ all_rom }}</textarea>
            </div>
        </div>
        <div class="button_wrap">
            <div class="buttons_add_lyrics">
                <div>
                    <button type="button" id="add_eng">Add ENG</button>
                    <button type="button" id="add_rom">Add ROM</button>
                </div>
                <div class="submit_lyrics">
                    <input type="submit" class="submitlyric" value="Next">
                </div>
            </div>
        </div>
    </form>
{% endblock %}
{% block script %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static "javascript/enter_all_lyrics.js" %}"></script>
{% endblock %}

Kasa/templates/Kasa/song_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/song_detail.css" %}"/>
{% endblock %}

{% block content %}
    <div class="songinfowrap">
        <div class="album-art">
            <a href="{% url 'Kasa:album_detail' song.album.pk %}">
                <img class="album-jacket" src="{{ song.album.album_art.url }}"/>
            </a>
        </div>
        <div class="infowrap">
            <div class="songtitle">{{ song.sname }}</div>
            <div class="song-artist"><a class="song-artist info_a"
                                        href="{% url 'Kasa:group_detail' album.group.pk %}">{{ album.group }}</a></div>
            <div class="albumname"><a class="albumname info_a"
                                      href="{% url 'Kasa:album_detail' album.pk %}">{{ album.aname }}</a></div>
        </div>
    </div>


    <div class="middlewrap">

        <div class="lyrics">
            <div class="lyrictitlewrap">
                <div class="lyricstitle">Lyrics</div>
                <div class="lyric-a"><a class="editlyric" href="{% url 'Kasa:enter_all_lyrics' song.id %}">Edit+</a>
                </div>
            </div>
            <div class="buttonwrap">
                <button type="button" id="Klyric" class="koreanlyric" value="on" onclick="Displaylyrics(this)">
                    Korean
                </button>
                <button type="button" id="Elyric" class="Englishlyric" value="off"
                        onclick="Displaylyrics(this)">English
                </button>
                <button type="button" id="Rlyric" class="Romlyric" value="off" onclick="Displaylyrics(this)">Rom
                </button>
                <button type="button" class="member" value="off" onclick="active_button(this)">Part</button>

            </div>
            {% for lyrics in all_lyrics %}
                <div class="korlyrics" id="Klyric{{ forloop.counter }}"
                     value="{% for each in lyrics.singer.all %}{{ each }}.{% endfor %}">
                    {{ lyrics.kor }}
                </div>
                <div class="englyriscs" id="Elyric{{ forloop.counter }}"
                     value="{% for each in lyrics.singer.all %}{{ each }}.{% endfor %}">
                    {{ lyrics.eng }}
                </div>
                <div class="romlyrics" id="Rlyric{{ forloop.counter }}"
                     value="{% for each in lyrics.singer.all %}{{ each }}.{% endfor %}">
                    {{ lyrics.rom }}
                </div>
            {% endfor %}
        </div>

        <div class="rightwrap">
            <div class="selection_part">
                {% for member in members %}
                    <div class="target{{ forloop.counter0 }}">{{ member.sname }}</div>
                {% endfor %}
            </div>
            {% if youtube_url %}
                <div class="mediatitle">Official movie</div>
                <iframe id="media" width="100%" height="200px" src="{{ youtube_url }}" frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
            {% endif %}
            {% if dance_url %}
                <div class="stagetitle">Stage movie</div>
                <div id="media">
                    <object class="youtube_1" type="text/html" data="{{ dance_url }}" allowFullScreen></object>
                </div>
            {% endif %}
            {% if soundcloud_url %}
                <div class="musictitle">Music</div>
                <div id="media">
                    <object class="youtube_1" type="text/html" data="{{ soundcloud_url }}" allowFullScreen></object>
                </div>
            {% endif %}

            <div class="snstitle">Twitter</div>
            <div class="twitter_container">
                <div class="twitterwrap">
                    <div class="twitter_url">
                        <a class="twitter-timeline" href="{{ sns }}">Tweets by BTS_twt</a>
                        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottomwrap">
        <div class="commenttitle">Comments</div>
        <div>
            {% if user.is_authenticated %}
                <div class="comment_wrapper">
                    <form action="{% url "Kasa:write_new_comment" %}" method="POST" class="">
                        <div class="submit-comment">
                            {% csrf_token %}
                            <input class="comment_content" name="comment_content"
                                   placeholder="write comments" autocomplete="off">
                            <input type="submit" class="submit" value="Write">
                            <input type="hidden" class="song_id" name="song_id" value="{{ song.id }}">
                        </div>
                    </form>
                </div>
            {% else %}
                <a class="comment-login" href="{% url "accounts:login" %}?next={{ request.path }}">로그인</a>
            {% endif %}
        </div>
        <div class="commentbox">
            {% for comment in comments %}
                <div class="each_comment">
                    <div class="userinfo">
                        <div class="username">{{ comment.user.username }}</div>
                        <div class="comment-time">{{ comment.created_at }}</div>
                    </div>
                    <div class="comment_contents">{{ comment.content }}</div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

{% block script %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{% static "javascript/song_detail.js" %}"></script>
    <script language="JavaScript" type="text/javascript">
        /*
                function active_explanation(btn) {
                    if (btn.getAttribute('value') === 'off') {
                        btn.setAttribute('value', 'on');

                        var have_explain = '{% for lyrics in all_lyrics %}{% for explain in lyrics.lyrics_explanation.all %}{{ lyrics.order }}.{% if explain %}{% endif %}{% endfor %}{% endfor %}';
                var have_explain_list = have_explain.split('.');
                console.log(have_explain_list);


                $('.explanation_box').css('display','block');
                $('.explanation_box').stop().animate({
                    'height':'100px',
                },500)

            }
        }
        */


        function active_button(target) {
            if (target.getAttribute('value') === 'off') {
                var singer_name = {}
                var length = '{{ members|length }}'
                var member_list = '{% for member in members %}{{ member.sname }},{% endfor %}'.split(',');
                for (member in member_list) {
                    singer_name[member_list[member]] = member;
                }

                target.setAttribute('value', 'on')
                $('.' + target.className).css({"background": "#00b8ff", "color": "white"})
                $('.selection_part').css('display', 'block');
                $('.korlyrics, .englyriscs, .romlyrics').mouseover(this,
                    function () {
                        var members = this.getAttribute('value')
                        var parts = members.split('.');
                        for (var part of parts) {
                            $('.target' + singer_name[part]).css({
                                "background": "#00b8ff",
                                "color": "white",
                            });

                        }
                    }
                )
                $('.korlyrics, .englyriscs, .romlyrics').mouseout(this,
                    function () {
                        $('.selection_part > div').css({"background": "white"});
                        $('.selection_part > div').css({"color": "black"});


                    }
                )

            } else if (target.getAttribute('value') === 'on') {
                target.setAttribute('value', 'off')
                $('.' + target.className
                ).css({"background": "#00fffe", "color": "black"})
                $('.selection_part').css('display', 'none');
                $('.korlyrics, .englyriscs, .romlyrics').unbind('mouseover')

            }
        }


        function Displaylyrics(obj) {
            var length = '{{ all_lyrics|length }}';
            var id_list = ['Klyric', 'Elyric', 'Rlyric'];

            var lang = obj.id;
            var cname = obj.className;

            var buffer_count = $('#' + lang + '1').prev().css('padding-left');
            if (!buffer_count)
                buffer_count = '0px';
            var buffer = Number(buffer_count.replace('px', ''));
            var inner = '0px';

            var inner = String(buffer + 20) + 'px';
            if (($('#' + id_list[0]).attr('value') === 'off' && $('#' + lang).prev().attr('value') === 'off') || (!$('#' + lang).prev().attr('value'))) {
                inner = '0px';
            }

            var refill_buffer = []
            var target = "#" + lang + '1';
            var next_classname = $(target).next().attr('class');
            while (next_classname !== 'korlyrics') {
                buffer_count = $(target).next().css('padding-left');
                refill_buffer.push(Number(buffer_count.replace('px', '')));
                target = "#" + $(target).next().attr('id');
                next_classname = $(target).next().attr('class');
            }
            for (var i = 1; i <= length; i++) {
                var check = $("#" + lang + i).css("display");

                if (check === 'none') {
                    $("#" + lang + i).css({"padding-left": inner});
                    // lyrics animate
                    $("#" + lang + i).css({'display': 'block'});
                    $("#" + lang + i).stop().animate({
                        'line-height': '1.5em', 'opacity': '1'
                    }, {
                        queue: false,
                        duration: 500,
                    });

                    var round = 0;
                    var index = id_list.indexOf(lang);
                    for (var order = index + 1; order < id_list.length; order++) {
                        var value = refill_buffer[round];
                        if (value <= 0 && $('#' + id_list[order]).attr('value') === 'off') {
                            round += 1;
                            continue;
                        }
                        var outer = String(value + 20) + 'px';

                        $('#' + id_list[order] + i).stop().animate({
                            'padding-left': outer,
                        }, {
                            queue: false,
                            duration: 500,
                        });
                        round += 1;
                    }
                } else {
                    $("#" + lang + i).stop().animate({
                        'line-height': '0',
                        'opacity': '0',
                        'padding-left': '0',
                    }, {
                        queue: false,
                        duration: 500,
                    });

                    var round = 0;
                    var index = id_list.indexOf(lang);
                    for (var order = index + 1; order < id_list.length; order++) {
                        var value = refill_buffer[round];
                        if (value <= 0) {
                            round += 1;
                            continue;
                        }
                        $('#' + id_list[order] + i).stop().animate({
                            'padding-left': String(value - 20) + 'px',
                        }, {
                            queue: false,
                            duration: 500,
                        });
                        round += 1;
                    }
                    $("#" + lang + i).css({'display': 'none'});
                }
            }
            if ($('.' + cname).attr('value') === 'off') {
                $('.' + cname).attr('value', 'on');
                $('.' + cname).css({"background": "#00b8ff", "color": "white"});
            } else if ($('.' + cname).attr('value') === 'on') {
                $('.' + cname).attr('value', 'off');
                $('.' + cname).css({"background": "#00fffe", "color": "black"});
            }
        }
    </script>
{% endblock %}