Kasa/urls.py
from django.urls import path
from Kasa import views

app_name = 'Kasa'

urlpatterns = [
    path('', views.main, name='main'),
    path('search/', views.search, name='search'),
    path('song/<int:song_pk>/', views.song_detail, name='song_detail'),
    path('singer/<int:singer_pk>', views.singer_detail, name='singer_detail'),
    path('group/<int:group_pk>', views.group_detail, name='group_detail'),
    path('album/<int:album_pk>', views.album_detail, name='album_detail'),
    path('comment/new/', views.write_new_comment, name='write_new_comment'),
    path('edit/<int:song_id>/stage1/', views.enter_all_lyrics, name='enter_all_lyrics'),
    path('edit/<int:song_id>/stage2/', views.modify_and_create_each_lyrics, name='modify_and_create_each_lyrics'),
]

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('reset_pw/', views.reset_pw.as_view(), name='reset_pw'),
    path('reset_pw/done/', views.reset_pw_done.as_view(), name='reset_pw_done'),
    path('reset/<uidb64>/<token>/', views.reset_pw_confirm.as_view(), name='reset_pw_confirm'),
    path('reset_pw/complete/', views.reset_pw_complete.as_view(), name='reset_pw_complete'),
    path('change_info/', views.change_info, name='change_info'),
    path('check_comment/', views.check_comment, name='check_comment'),
    path('check_comment/del/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    alias = models.CharField(max_length=255, unique=True, null=True, verbose_name='닉네임')
    interest = models.CharField(max_length=255, blank=True, verbose_name='관심사')

accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordResetForm as DefaultPasswordResetForm, SetPasswordForm as DefaultSetPasswordForm
from accounts.models import User
from django.utils.translation import     gettext_lazy as _


class UserForm(forms.ModelForm):
    verify_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User

        fields = ['username', 'email', 'password', 'alias', 'interest']
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Within 15 characters', 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'alias': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Within 10 characters', 'autocomplete': 'off'}),

            'interest': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
        }
        labels = {
            'username': 'ID',
            'email': 'E-mail',
            'password': 'Password',
            'alias': 'Nickname',
            'interest': 'Favorite Group',

        }

    field_order = ['username', 'email', 'password', 'verify_password', 'alias', 'interest']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['maxlength'] = 15
        self.fields['alias'].widget.attrs['maxlength'] = 10

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Id already exsists.')

        return username

    def clean_alias(self):
        alias = self.cleaned_data['alias']
        if User.objects.filter(alias=alias).exists():
            raise forms.ValidationError('Nickname already exsists.')

        return alias

    def clean_verify_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('verify_password')
        if password1 != password2:
            raise forms.ValidationError('Passwords must match')
        return password2


class InfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'alias', 'interest']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'alias': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Within 10 characters', 'autocomplete': 'off'}),
            'interest': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),

        }
        labels = {
            'email': 'Email',
            'alias': 'Nickname',
            'interest': 'Favorite Group',
        }

    def __init__(self, *args, **kwargs):
        super(InfoForm, self).__init__(*args, **kwargs)
        self.fields['alias'].widget.attrs['maxlength'] = 10

    def clean_alias(self):
        alias = self.cleaned_data['alias']
        if User.objects.filter(alias=alias).exists():
            raise forms.ValidationError('Nickname already exsists.')
        return alias


class PasswordResetForm(DefaultPasswordResetForm):
    email = forms.EmailField(label="E-mail", max_length=254)

    def clean_email(self):
        email = self.cleaned_data["email"]
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("The e-mail address is not assigned"
                                          " to any user account"))
        return self.cleaned_data["email"]

class SetPasswordForm(DefaultSetPasswordForm):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label="New password confirmation",
        strip=False,
        widget=forms.PasswordInput,
    )

accounts/views.py
from django.contrib.auth import authenticate
from django.contrib import auth
from django.contrib.auth.hashers import check_password
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordChangeDoneView
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from Kasa.models import Comments
from accounts.decorators import login_required
from accounts.forms import InfoForm, UserForm, PasswordResetForm, SetPasswordForm
from accounts.models import User
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import get_user_model

UserModel = get_user_model()


# 로그인 뷰
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            next_url = request.POST.get('next_url', 'accounts:login')
            if next_url == '/search/':
                next_url = ''
            return redirect(next_url)
            # return redirect('accounts:login')
        else:
            errors = True
            context = {
                'errors': errors
            }
            return render(request, 'accounts/login.html', context)
    else:
        context = {
            'next_url': request.GET.get('next', 'accounts:login'),
        }
        return render(request, 'accounts/login.html', context)


# 로그아웃 뷰
@login_required
def logout(request):
    next_url = request.GET.get('next', 'accounts:login')
    if next_url == '/search/':
        next_url = '/'
    auth.logout(request)
    return redirect(next_url)


# 회원가입 뷰
def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'],
                                                form.cleaned_data['password'])
            new_user.alias = form.cleaned_data['alias']
            new_user.interest = form.cleaned_data['interest']
            new_user.save()
            user = authenticate(username=new_user.username, password=request.POST['verify_password'])
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')

            return redirect('accounts:login')
        else:
            form = UserForm(request.POST)
            context = {
                'form': form,
            }
            return render(request, 'accounts/signup.html', context)
    else:
        form = UserForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/signup.html', context)


# 비밀번호 변경 뷰
@login_required
def change_pw(request):
    context = {}
    if request.method == "POST":
        current_password = request.POST['origin_password']
        user = request.user
        if check_password(current_password, user.password):
            new_password = request.POST['password1']
            password_confirm = request.POST['password2']
            if new_password == password_confirm:
                user.set_password(new_password)
                user.save()
                auth.login(request, user)
                return redirect('accounts:login')
            else:
                context.update({
                    'error': "새로운 비밀번호를 다시 확인해주세요."
                })
        else:
            context.update({
                'error': "현재 비밀번호가 일치하지 않습니다."
            })
    return render(request, 'accounts/change_pw.html', context)


# 비밀번호 초기화 뷰
class reset_pw(PasswordResetView):
    template_name = "accounts/reset_pw.html"
    form_class = PasswordResetForm
    success_url = reverse_lazy('accounts:reset_pw_done')
    email_template_name = 'accounts/password_reset_email.html'
    # html_email_template_name = 'accounts/password_reset_email.html'


# 비밀번호 초기화 완료 뷰 / 메일 발송 완료
class reset_pw_done(PasswordResetDoneView):
    template_name = "accounts/reset_pw_done.html"


# # 비밀번호 초기화 메일로 들어온 URL 처리
# # 새로운 비밀번호 설정 뷰
class reset_pw_confirm(PasswordResetConfirmView):
    template_name = 'accounts/reset_pw_confirm.html'
    success_url = reverse_lazy("accounts:login")
    form_class = SetPasswordForm

    def get_user(self, uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist, ValidationError):
            user = None
        return user


# 새로운 비밀번호 설정 완료 뷰
class reset_pw_complete(PasswordChangeDoneView):
    template_name = "accounts/reset_pw_complete.html"
    success_url = reverse_lazy("accounts:login")


#
# 닉네임, 관심사에 대한 정보 변경 뷰
@login_required
def change_info(request):
    if request.method == "POST":
        form = InfoForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        else:
            form = InfoForm(request.POST)
            context = {
                'form': form
            }
            return render(request, 'accounts/change_info.html', context)
    else:
        form = InfoForm(instance=request.user)
        context = {
            'form': form
        }
        return render(request, 'accounts/change_info.html', context)


# 사용자가 작성한 댓글들 확인하는 뷰
@login_required
def check_comment(request):
    comments = Comments.objects.filter(user=request.user).order_by('-created_at')
    context = {
        'comments': comments
    }

    return render(request, 'accounts/check_comment.html', context)


# 특정 댓글 삭제 뷰
@login_required
def delete_comment(request, comment_pk):
    comment = get_object_or_404(Comments, pk=comment_pk)

    # 요청을 보낸 사용자와 comment 작성자가 같은지 확인
    # 한번의 검증단계(굳이 필요없을 수도...)
    if comment.user.pk == request.user.pk:
        comment.delete()

    return redirect('accounts:check_comment')

accounts/templates/accounts/change_info.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/change_info.css" %}"/>
{% endblock %}

{% block content %}
    <div class="flexwrap">
    <div class="change_info_wrap">
        <div class="change_info_title">
            Change Information
        </div>
        <form action="" method="POST" class="form">
            {% csrf_token %}
            {% for field in form %}
                <div class="field_wrap">
                    <div class="field_label">{{ field.label }}</div>
                    <div class="field_specific">{{ field }}</div>
                </div>
            {% endfor %}
            <input type="submit" class="change_info_submit" value="Change">
        </form>
        {% for label in form %}
            {% if label.errors %}
                {% for error in label.errors %}
                    <div class="change_info_error">Error : {{ error }}</div>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/change_pw.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/change_pw.css" %}"/>
{% endblock %}
{% block content %}
    <div class="changepw_wrap">
        <div class="error_message">
            {{ error }}
        </div>

        <div class="chagepwtitle">
            Change password
        </div>
        <form action="" method="POST" class="form">
            {% csrf_token %}
            <div class="wrap_2">
                <div class="username_form_text">
                    <div class="change_pw_username">Origin Password</div>
                    <input class="login_input" name="origin_password" type="password"
                           placeholder="Enter your Origin Password">
                </div>
                <div class="password_form_text">
                    <div class="change_pw_password">New Password</div>
                    <input class="login_input" name="password1" type="password" placeholder="Enter your New Password">
                </div>
                <div class="password_form_text">
                    <div class="change_pw_password">Confirm Password</div>
                    <input class="login_input" name="password2" type="password" placeholder="Please Confirm">
                </div>
                <input type="submit" class="login_btn" value="Change password">
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/check_comment.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/check_comment.css" %}"/>
{% endblock %}

{% block content %}
    <div class="comments_field">
        <div class="comment_wrap">
            <div class="comment_title">
                My comment
            </div>
            {% if comments %}
                <div class="each_comment">
                    {% for comment in comments %}
                        <div class="each_comment_wrap">
                            <div class="song_name">
                                {{ comment.song.sname }}
                            </div>
                            <div class="content">
                                {{ comment.content }}
                            </div>
                            <div class="created_at">
                                {{ comment.created_at }}</div>
                            <div class="delete_btn">
                                <a class="delete_btn_a"
                                   href="{% url 'accounts:delete_comment' comment.pk %}">Delete</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="change_pw_password">작성한 댓글이 없습니다.</div>
            {% endif %}

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}"/>
{% endblock %}
{% block content %}
    <div class="logincenter_wrap">
        <div class="loginwrap">
            {% if user.is_authenticated %}
                <div class="signup_welcome">Welcome, {{ user.alias }}</div>
                <div class="signup_explanation">Kasa is best way to find Kpop lyrics of your favorite Kpop artists. Here
                    we
                    provide you over 10 Kpop songs and lyrics. What do you expect?
                </div>
                <div class="signup_btns_wrap">
                    <div class="signup_buttons"><a href="{% url 'accounts:logout' %}">Sign out</a></div>
                    <div class="signup_buttons"><a href="{% url 'accounts:change_pw' %}">Change password</a></div>
                    <div class="signup_buttons"><a href="{% url 'accounts:change_info' %}">Change info</a></div>
                    <div class="signup_buttons"><a href="{% url 'accounts:check_comment' %}">My comments</a></div>
                </div>
            {% else %}

                <div class="sign_in_talk">Sign in to Kasa</div>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="memeberlogin">
                        <div class="id_wrap">
                            <div class="id_notation">ID</div>
                            <input type="text" class="id_text" name="username" autocomplete=off placeholder="Enter ID">
                        </div>
                        <div class="password_wrap">
                            <div class="password_and_find">
                                <div class="password_notation">Password</div>
                                <div class="findpassword">
                                    <a href="{% url 'accounts:reset_pw' %}" class="findp">forgot password?</a>
                                </div>
                            </div>
                            <input type="password" class="password_text" name="password" placeholder="Enter Password">
                        </div>
                        <input type="hidden" class="next_url" name="next_url" value="{{ next_url }}">
                        <button type="submit" class="submit" value="sign in">Sign in</button>
                    </div>
                    {% if errors %}
                        <p class="unmatch">Incorrect ID or Password / Please try again</p>
                    {% endif %}
                </form>
                <div class="center">
                    <div class="empty_line"></div>
                </div>
                <div class="sign_in_talk_2">Sign in with social account</div>
                <div class="sociallogin">
                    <a href="{% provider_login_url 'google' %}" class="google" name=""
                       value="sign in with google"><img src="{% static 'image/google-hangouts.png' %}"/>
                        &nbsp;&nbsp;&nbsp;Sign in with Google</a>
                    <a href="{% provider_login_url 'kakao' %}" class="kakao" name=""
                       value="sign in with kakao"><img src="{% static 'image/kakao-talk.png' %}"/>
                        &nbsp;&nbsp; Sign in with Kakao</a>
                </div>
                <div class="signupbutton">
                    <div class="dont_have_yet">Don't have account yet?</div>
                    <a href="{% url 'accounts:signup' %}" class="signb">Sign up!</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktrans %}You're receiving this email because you requested a password reset for your user account at
        {{ site_name }}.{% endblocktrans %}

    {% trans "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'accounts:reset_pw_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

    {% trans "Thanks for using our site!" %}

    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/reset_pw.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/reset_pw.css" %}"/>
{% endblock %}
{% block content %}
    <div class="resetpw_wrap">
        <div class="resetpw_title">
            Reset Password
        </div>
        <form action="" method="POST" , class="form">
            {% csrf_token %}
            <div class="resetpw_explanation">
                Seems like you forgot your password for Kasa! But don't worry. You can reset your password by entering
                your email address. We will send you an email with temporary password.
            </div>

            {% for label in form %}
                {% if label.errors %}
                    {% for error in label.errors %}
                        <div class="rpw_error">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            {% endfor %}

            {% for field in form %}
                <div class="field_wrap">
                    <div class="field_label">{{ field.label }}</div>
                    <div class="field_specific">{{ field }}</div>
                </div>
            {% endfor %}
            <input type="submit" class="resetpw_submit" value="Send Email">
        </form>


    </div>
{% endblock %}

accounts/templates/accounts/reset_pw_complete.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/reset_pw_complete.css" %}"/>
{% endblock %}
{% block content %}
    <dev class="flexwrap">
        <div class="rpw_complete_wrap">
            <div class="rpw_complete_title">Reset Successfully</div>
            <div class="rpw_complete_explanation">
                Please sign in again
            </div>
            <input type="submit" class="rpw_complete_submit" value="Sign in">
            <div class="line"></div>
            <div class="logo"><a id="logo" href="{% url 'Kasa:main' %}"> <img
                    src="{% static 'image/logo.png' %}"></a></div>
        </div>
    </dev>
{% endblock %}

accounts/templates/accounts/reset_pw_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load i18n static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/reset_pw_confirm.css" %}"/>
{% endblock %}

{% block content %}

    <div class="rpw_confirm_wrap">
        <div class="rpw_confirm_title">{% if token_fail %}Link was invalid{% else %}Reset Password{% endif %}</div>

        {% if token_fail %}
            {% url 'account_reset_password' as passwd_reset_url %}
            <div>The password reset link was invalid, possibly because it has already been used. Please
                request a <a href="{% url 'accounts:reset_pw' %}">new password reset</a>.
            </div>
        {% else %}
            {% if form %}
                <form method="POST" action="{{ action_url }}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field_wrap">
                            <div class="field_label">{{ field.label }}</div>
                            <div class="field_specific">{{ field }}</div>
                        </div>
                    {% endfor %}
                    <input type="submit" class="rpw_confirm_email" value="Confirm">
                </form>
                    {% for label in form %}
                        {% if label.errors %}
                            {% for error in label.errors %}
                                <div class="rpw_error">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}

            {% else %}
                <div class="rpw_done_explanation">Your password is now changed.</div>
            {% endif %}
        {% endif %}

    </div>
{% endblock %}
{#{% if validlink %}#}
{##}
{#<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>#}
{##}
{#<form method="post">{% csrf_token %}#}
{#<fieldset class="module aligned">#}
{#    <div class="form-row field-password1">#}
{#        {{ form.new_password1.errors }}#}
{#        <label for="id_new_password1">{% trans 'New password:' %}</label>#}
{#        {{ form.new_password1 }}#}
{#    </div>#}
{#    <div class="form-row field-password2">#}
{#        {{ form.new_password2.errors }}#}
{#        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>#}
{#        {{ form.new_password2 }}#}
{#    </div>#}
{#    <input type="submit" value="{% trans 'Change my password' %}">#}
{#</fieldset>#}
{#</form>#}
{##}
{#{% else %}#}
{##}
{#<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>#}
{##}
{#{% endif %}#}
{#{% endblock %}#}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}

accounts/templates/accounts/reset_pw_done.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/reset_pw_done.css" %}"/>
{% endblock %}

{% block content %}
    <div class="rpw_done_wrap">
        <div class="rpw_done_title">Sent you an email</div>
        <div class="rpw_done_explanation">We've sent you an Email.</div>
        <div class="rpw_done_explanation">Please check your mailbox.</div>
        <div class ="line"></div>
        <div class="logo"><a id="logo" href="{% url 'Kasa:main' %}"> <img
                src="{% static 'image/logo.png' %}"></a></div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/signup.css" %}"/>
{% endblock %}
{% block content %}
    <div class="signupwrap">
        {% if user.is_authenticated %}
            <script type="text/javascript">
                alert('Sign out required for sign up.')
            </script>
        {% else %}
            <div class="signup_title">Sign up to Kasa</div>
            <form action="" method="POST" class="form">
                {% csrf_token %}
                <div class="signup_wrap_2">
                    {{ field.label }}
                    {% for field in form %}
                        <div class="field_wrap">
                            <div class="field_label">{{ field.label }}</div>
                            <div class="field_specific">{{ field }}</div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="signupbutton">Sign up</button>
                </div>
            </form>
            {% for label in form %}
                {% if label.errors %}
                    {% for error in label.errors %}
                        <div class="signup_error">Error : {{ error }}</div>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}