Kasa/urls.py
from django.urls import path
from Kasa import views

app_name = 'Kasa'

urlpatterns = [
    path('', views.main, name='main'),
    path('search/', views.search, name='search'),
    path('song/<int:song_pk>/', views.song_detail, name='song_detail'),
    path('singer/<int:singer_pk>', views.singer_detail, name='singer_detail'),
    path('group/<int:group_pk>', views.group_detail, name='group_detail'),
    path('album/<int:album_pk>', views.album_detail, name='album_detail'),
    path('comment/new/', views.write_new_comment, name='write_new_comment'),
    path('edit/<int:song_id>/stage1/', views.enter_all_lyrics, name='enter_all_lyrics'),
    path('edit/<int:song_id>/stage2/', views.modify_and_create_each_lyrics, name='modify_and_create_each_lyrics'),
]

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('reset_pw/', views.reset_pw.as_view(), name='reset_pw'),
    path('reset_pw/done/', views.reset_pw_done.as_view(), name='reset_pw_done'),
    path('reset/<uidb64>/<token>/', views.reset_pw_confirm.as_view(), name='reset_pw_confirm'),
    path('reset_pw/complete/', views.reset_pw_complete.as_view(), name='reset_pw_complete'),
    path('change_info/', views.change_info, name='change_info'),
    path('check_comment/', views.check_comment, name='check_comment'),
    path('check_comment/del/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Jua|Poor+Story&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Squada+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <title>Kasa, Best way to find K-pop lyrics</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/navbar.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/footer.css" %}"/>
    <link rel="icon" href="{% static 'image/favicon.ico' %}">
    {% block style %}
    {% endblock %}

</head>
<body>

{% include 'navbar.html' %}

<div class="wrap" id="wrap">
    {% block content %}
    {% endblock %}
</div>

{% include 'footer.html' %}

{% block script %}
{% endblock %}

</body>
</html>

templates/footer.html
{% load static %}
<div class="footerwrap">
    <div class="footer">
        <div class="developer">&copy; Kasa | &nbsp; &nbsp; &nbsp; &nbsp; Kwon Kusang&nbsp;<a href="https://github.com/rnjsrntkd95"><i class="fab fa-github"></i></a>

            &nbsp; &nbsp; &nbsp; &nbsp; Jung Seunghyun&nbsp;<a href="https://github.com/herrakam"><i class="fab fa-github"></i></a>
            &nbsp; &nbsp;
            &nbsp; &nbsp; Shin Woochul&nbsp;<a href="https://github.com/swc0620"><i class="fab fa-github"></i></a>

            &nbsp; &nbsp; &nbsp; &nbsp; Song Minho&nbsp;<a href="https://github.com/pot1223"><i class="fab fa-github"></i></a>
        </div>
        <div class="background-footer" style=" background-image: url({% static 'image/background-bottom.png' %})"></div>
    </div>
</div>

templates/navbar.html
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static "css/navbar.css" %}"/>
{% endblock style %}

<nav>
    <div class="navlist">
        <div class="title"><a id="title_a_tag" href="{% url 'Kasa:main' %}"> <img
                src="{% static 'image/logo.png' %}"></a></div>
        <div class="search-box-wrapper">
            <form action="{% url 'Kasa:search' %}" method="GET">
                {% csrf_token %}
                <div class="search-box">
                    <input type="text" id="search" class="search-txt" name="kwd" placeholder="Search" autocomplete="off">
                    <input type="image" src="   {% static 'image/magnifying_glass.png' %}" alt="submit" name="submit"
                           value="submit"
                           class="search-btn">
                </div>
            </form>
        </div>
        {% if user.is_authenticated %}
            <div class="signin"><a href="{% url 'accounts:login' %}">Edit</a></div>
            <div class="signup"><a href="{% url 'accounts:logout' %}?next={{ request.path }}">Sign out</a></div>
        {% else %}
            <div class="signin"><a href="{% url 'accounts:login' %}?next={{ request.path }}">Sign in</a></div>
            <div class="signup"><a href="{% url 'accounts:signup' %}">Sign up</a></div>
        {% endif %}
    </div>
</nav>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Best way to find K-pop lyrics Kasa</title>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <style>
        html {
            font-family: "Aller Light";
            position: relative;
            min-height: 100%;
            margin: 0;
            background:white;
             }
        body {
            min-height: 100%;
            margin:0 0 10px 0;
            padding-bottom: 100px;
            }
        nav {
            width:100%;
            background: black;
            font-weight: bold;
        }
        nav .navlist{
            display:flex;
            flex-direction:row;
            {#padding:0px 40px 0px 0px;#}
            margin:0;
            list-style:none;
            list-style-type:none;
            align-items:center;
        }
        nav .navlist .title{
            font-size:3em;
            padding:0px 0px 0px 50px;
            /*vertical-align: bottom;*/
            /*align-items:center;*/
        }
        nav .navlist .signin:hover, nav .navlist .signup:hover{
            border-bottom:2px solid;
        }
        nav .navlist .title, .signin, .signup{
            float:left;
        }
        nav .navlist .title{
            margin-right:auto;
        }
        nav .navlist .title a, nav .navlist .signin a, nav .navlist .signup a{
            width:60px;
            display:block;
            padding:10px 10px;
            text-decoration:none;
            color:white;
            text-align:center;
        }

        nav .navlist .signup a {
            margin-right : 50px;
        }

        nav .navlist .signin a {
            margin-right: 10px;
        }

        nav .navlist #title_a_tag {
            width:138px;
            height: 45px;
            display:block;
            padding:10px 10px;
            text-decoration:none;
            color:white;
            text-align:center;
            }

        nav .navlist .search-box{
            margin-right: 50px;
            padding: 5px;
            {#position: absolute;#}
            {#top: 8px;#}
            {#right:220px;#}
            height: 25px;
            background-color: #ffffff;
            border: 2px solid #00fffe;
            border-radius: 30px;
            transition: 0.4s;
            width:30px;
        }
        nav .navlist .search-box:hover{
            box-shadow: 0px 0px 10px 1px #51e3d4;
            border: 2px solid #00fffe;
            width: 300px;
        }
        nav .navlist .search-box .search-btn{
            text-decoration: none;
            float: right;
            padding-top : 2px;
            width: 27px;
            height: 27px;
            background-color: white;
            border-radius: 50%;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #00fffe;
        }
        nav .navlist .search-box:hover > .search-btn{
            background-color: #ffffff;
        }

        nav .navlist .search-box .search-txt{
            display: flex;
            padding: 0;
            width: 0px;
            border:none;
            background: none;
            outline: none;
            float: left;
            font-size: 1rem;
            line-height: 30px;
            transition: .4s;
        }
        nav .navlist .search-box:hover > .search-txt{
            width: 240px;
            padding: 0 6px;
        }
        .wrap{
            width:500px;
            margin:auto;
            background-color: white;
            padding:0px;
        }
        form{
            padding:10px;
            margin:10px;
        }
        h2{
            text-align: center;
            color: black;
            font-size:3em;
            font-family:Aller;
            padding: 10px;
            border-radius: 30px;
        }
        .name,.email,.password,.repassword,.mnumber{
               border:0;
              background:none;
            display:block;
             margin:40px auto;
             text-align: center;
             border-bottom:2px solid black;
            padding:5px 10px;
            outline:none;
            color:black;
            transition: 0.25s;position: static;
            font-size:1.5em;
            border-color:black;position: static;
            font-size:1em;

        }
        input[type=text], input[type=email], input[type=number], input[type=password]{
            width:90%;
        }
        input[type=submit]{
            width:95%;
            background-color: white;
            cursor: pointer;
            font-size: 18px;
            font-weight: bold;
            color:black;
            padding:10px;
            border-radius: 30px;
            border: 2px solid #00fffe;
            transition: 0.25s;
        }
        input[type=submit]:hover{
            background-color: #00fffe;
        }
        select{
            padding:10px;
            width:32%;
            border-radius: 30px;
        }

        footer {
            position: absolute;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 60px;
            text-align: center;
            color: gray;
            font-weight:bold;
            }
    </style>
</head>
<body>
<nav>
    <div class = "navlist">
        <div class="title"><a id="title_a_tag" href="#"> <img src="../../../templates/KakaoTalk_20200204_155442069.png"></a></div>
        <div class="search-box">
            <input type="text" class="search-txt" name="" placeholder=" Search">
            <input type="image" src="../../../templates/KakaoTalk_20200206_174558346-1.png" alt="submit" class="search-btn">
        </div>
        <div class="signin"><a href="#">Sign in</a></div>
        <div class="signup"><a href="#">Sign up</a></div>
    </div>
</nav>
<div class="wrap">
    <form>
        <h2> SignUp</h2>
        <input class="name" type="text" name="yourname" placeholder="Your Name">
        <input class="email" type="email" name="email" placeholder="Your Email">
        <input class="mnumber" type="number" name="mnumber" placeholder="Mobile Number">
        <input class="password" type="password" name="password" placeholder="Password">
        <input class="repassword" type="password" name="conformpassword" placeholder="Conform Password">


        <span style ="font-size:18px;">Date of Birth</span>
        <br>
        <select name="DoBmonth">
            <option> Month</option>
            <option value="january">January</option>
            <option value="february">February</option>
        </select>

        <select name="DoBday">
            <option> Day</option>
            <option value="1">1</option>
            <option value="2">2</option>
        </select>

        <select name="DoByear">
            <option> Year</option>
            <option value="2000">2000</option>
            <option value="1990">1990</option>
        </select>
        <br>
        <br>
        <input type="radio" name="male" value="male">Male
        <input type="radio" name="female" value="female">Female
        <br>
        <input type="checkbox"> I Agree To The Terms of Use
        <br>
        <br>
        <br>
        <input type="submit" value="Submit Now">
    </form>
</div>


<footer class="footer">
    <div class="developer">피로그래밍 12기 &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 정승현 &nbsp &nbsp &nbsp &nbsp 권구상 &nbsp &nbsp &nbsp &nbsp 신우철 &nbsp &nbsp &nbsp &nbsp 송민호</div>

</footer>
</body>
</html>